### ISSUE TITLE
Grid only loades if rezised/rotated

### ISSUE THREAD

**Issue by kgb64** [SuchByte/Macro-Deck-Client#2]
Server: 2.8.1.220302118
Client: Ansroid App: 2.2.0 beta
           Web Client 2.2.0
The Grid doesnt load until the screen is rotated or rezised.

https://user-images.githubusercontent.com/88612147/151927407-0ed13c4c-d2ea-4e46-8f75-73fae4108989.mp4

https://user-images.githubusercontent.com/88612147/151927414-7f7909b9-7ab9-4f2f-a01a-7d12c5eee9a3.mp4

https://user-images.githubusercontent.com/88612147/151929286-93122312-38c9-4b79-a512-b6f59cb87cca.mp4

**Comment by SuchByte** [comment]
Please try to clear the cache or reinstall the app. Let me know if this fixed it.

**Comment by kgb64** [comment]
No it sadly didn't.
Alos i found the the connection is now listed as "Webclient" although i use the andriod app as client. (idk if its intended to be like that)
![image](https://user-images.githubusercontent.com/88612147/152221103-55af692d-0b01-4a05-ae04-3209b3b587e1.png)

**Comment by kgb64** [comment]
For some reason everything is working now. Im sorry for any inconveniences. All i did was:

- restore from the last backup
- icons dont show because of using a backup from an older server version, so u just have to click edit and then ok for every tile
- now it works flawlessly
